name: "Strawberry-ThinLTO-LTS"

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build Profile'
        required: true
        default: 'Server'
        type: choice
        options:
          - Server
          - General
  push:
    tags:
      - 'v*'

jobs:
  build:
    env: 
       GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps: 
      - name: Set up cache env vars
        id: cache-workspace-vars
        run: |
          echo "CACHE_WORKSPACE_KEY=${{ runner.os }}-workspace-${{ github.run_id }}" >> $GITHUB_ENV
          echo "CACHE_WORKSPACE_RESTORE_KEY=${{ runner.os }}-workspace-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set SUID to tar binary
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
      
      - name: Download Dockerfile
        run: |
         curl -fL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/Dockerfile -o Dockerfile
         curl -fL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/.dockerignore -o .dockerignore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache 
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Restore Cache of Github Workspace
        uses: actions/cache/restore@v4
        id: cache-restore-workspace
        with:
          path: ${{ github.workspace }}/kernel-source-host
          key: ${{ env.CACHE_WORKSPACE_RESTORE_KEY }}-ThinLTO

      - name: Check and make kernel-source-host directory
        run: | 
          cd ${{ github.workspace }}
          if [ ! -d kernel-source-host ]; then
            mkdir kernel-source-host
          fi

      - name: Check if repo was previously cloned
        id: check_repo
        run: |
          cd ${{ github.workspace }}/kernel-source-host
          if [ -d .git ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout ps4-linux-12xx repo
        if: steps.check_repo.outputs.exists == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/kernel-source-host
          ref: ${{ github.ref }}

      - name: Update ps4-linux-12xx repo if it exists
        if: steps.check_repo.outputs.exists == 'true'
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/kernel-source-host
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          fetch-depth: 1
          token: ${{ github.token }}
          persist-credentials: false
          clean: false

      - name: Move .github directory to workspace
        run: mv ${{ github.workspace }}/kernel-source-host/.github ${{ github.workspace }}/.github || true
      
      - name: Build Docker image with cache
        run: |
          mkdir -p /tmp/.buildx-cache
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --tag kernel-linux-ps4:latest \
            --load \
            .
      
      - name: Setup compile error problem-matching for kernel compilation
        run: echo "::add-matcher::.github/problem-matchers/kernel-compile-errors.json"

      - name: Set up Swapfile with Marketplace Actions
        uses: pierotofy/set-swap-space@fc79b3f67fa8a838184ce84a674ca12238d2c761
        with:
          swap-size-gb: 12

      - name: Compile the linux kernel with docker run
        id: compile-kernel-step
        run: |
          set +e

          docker run -i --name kernel -d -v ${{ github.workspace }}/kernel-source-host:/container/workspace/kernel-source-container \
          -w /container/workspace/kernel-source-container kernel-linux-ps4:latest tail -f /dev/null
          
          docker exec -i kernel bash <<EOF 
          set -e
          
          GH_INPUT_PROFILE="${{ inputs.profile }}"
          export TARGET_PROFILE="\${GH_INPUT_PROFILE:-Server}"
          
          echo "Executing build.sh with profile: \$TARGET_PROFILE"
          chmod +x build.sh
          
          ./build.sh --option 3 use=\$TARGET_PROFILE

          echo "Packaging build artifacts..."
          
          tar -cvzf /container/workspace/kernel-source-container/kernel.tar.gz -C out bzImage .config --owner=0 --group=0
          EOF
          
          cd ${{ github.workspace }}/kernel-source-host 
          echo "compile-kernel-complete=true" >> $GITHUB_OUTPUT
          set -e

      - name: Remove compile error problem-matching
        run: echo "::remove-matcher owner=kernel-compile-docker::"

      - name: Read Artifact Name
        id: read-artifact
        working-directory: ${{ github.workspace }}/kernel-source-host
        run: |
          echo "pkg_name=kernel.tar.gz" >> $GITHUB_OUTPUT

      - name: Upload kernel image to github actions artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.read-artifact.outputs.pkg_name }}
          path: ${{ github.workspace }}/kernel-source-host/${{ steps.read-artifact.outputs.pkg_name }}
          archive: false

      - name: Delete Cache of Github Workspace
        env:
          GH_TOKEN: ${{ github.token }}
        if: steps.cache-restore-workspace.outputs.cache-hit && steps.compile-kernel-step.outputs.compile-kernel-complete
        run: |
          gh cache delete --repo ${{ github.repository }} ${{ steps.cache-restore-workspace.outputs.cache-primary-key }} || true

      - name: Save Cache of Github Workspace
        uses: actions/cache/save@v4
        if: steps.compile-kernel-step.outputs.compile-kernel-complete
        with:
          path: ${{ github.workspace }}/kernel-source-host
          key: ${{ steps.cache-restore-workspace.outputs.cache-primary-key }}